apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
spec:
  destination:
    name: 'in-cluster'
    namespace: istio-system
    #server: 'https://7A0A2913B034E3E506C7C72C80CC60CD.gr7.us-west-2.eks.amazonaws.com'
  source:
    path: ''
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    targetRevision: 1.14.1
    chart: istiod
  project: infra-dev
