apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: istio-system # Your Coder deployment namespace
spec:
  acme:
    email: marcelo.bertho@wise.co
    preferredChain: ""
    privateKeySecretRef:
      name: example-issuer-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          route53:
            accessKeyID: AKIA6ONRFLMVIUKT3YVU #secret with IAM Role
            region: eu-central-1
            secretAccessKeySecretRef:
              key: secret-access-key
              name: awssm-secret #route53-credentials
        selector:
          dnsZones:
            - wise.co

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wise-co-dev-certs
  namespace: istio-system # Your Coder deployment namespace
spec:
  commonName: "*.wise.co"
  dnsNames:
    - "wise.co"
    - "*.wise.co"
  ClusterissuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: wise.co