apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-example
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: mberthos
  project: default
  source:
    path: ./project_example/
    repoURL: git@github.com:mberthos/hotmart-idp.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
