pipeline {
    agent {
       label "mestre"
    }

    stages {
        stage('Git Clone') {
           steps {
              echo "Running in mestre"
              sh "git clone https://mberthos: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@github.com/mberthos/hotmart-idp.git"
           }
        }

        stage ("Docker build") {
           agent{
             dockerfile {
                dir 'Dockerfiles'
                label "mestre"
             }
            }
            steps{
                sh "hostname"
            }
        }
    }
}

//

        /*stage ('Build and push image') {
            steps {
                script {
                    sudo docker build --build-arg NPM_TOKEN=${NPM_TOKEN} -t ${ECR}:${BUILD_NUMBER}-candidate .
                    sudo docker push ${ECR}:${BUILD_NUMBER}-candidate
                }
            }
        }

        stage('Deployng Kubernetes') {
            steps {
                script {
                   gcloud container clusters get-credentials cluster-sites-prod-3 --zone us-central1-c --project kenlo-project
                   kubectl apply -f sites-webapp-final.yaml
                   #kubectl apply -f sites-webapp2_final.yaml
                   kubectl apply -f services.yaml
                   kubectl apply -f gateway-istio.yaml
                   kubectl apply -f virtual_service-istio.yaml
                   kubectl apply -f destination_rule-istio.yaml
                }
            }
        } */

