apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: master-configs-infra-dev
  namespace: argocd
spec:
  destination:
    name: 'in-cluster'
    namespace: argocd
    server: ''
  source:
    path: ./argocd-install/mberthos/pos-setup/k8s
    repoURL: 'git@github.com:mberthos/hotmart-idp'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-dev
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Infra Dev

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  #destinations:
  #- '*'

  # Deny all cluster-scoped resources from being created, except for Namespace
  #clusterResourceWhitelist:
  #- group: ''
  #  kind: Namespace

  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  #namespaceResourceBlacklist:
  #- '*'

  # Deny all namespaced-scoped resources from being created, except for Deployment and StatefulSet
 # namespaceResourceWhitelist:
 # - group: 'apps'
 #   kind: Deployment
 # - group: 'apps'
 #   kind: StatefulSet

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false
