---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment-gaviao
  namespace: default
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        version: gaviao
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: testcontainers/helloworld
          ports:
            - containerPort: 8080
