
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: project-test-secrets
  namespace: default
spec:
  refreshInterval: 30m # rate SecretManager pulls GCPSM
  secretStoreRef:
    name: secretstore-aws # name of the SecretStore (or kind specified)
    kind: ClusterSecretStore
  target:
    name: project-test-secrets # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: project-test-secrets  # name of the GCPSM secret key
      remoteRef:
        key: project-test-secrets