apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-example
  labels:
    app: project-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-example
  template:
    metadata:
      labels:
        app: project-example
    spec:
      containers:
        - name: project-example
          image: 767828761310.dkr.ecr.us-east-2.amazonaws.com/hotmart-sre:1.0.2
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: project-example
---
apiVersion: v1
kind: Service
metadata:
  name: project-example
  namespace: mberthos
  labels:
    logging: loki
    app: project-example
    service: project-example
spec:
  selector:
    app: project-example
  ports:
    - port: 80
      name: http
      targetPort: 80

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: project-example
  namespace: mberthos
spec:
  refreshInterval: 30m # rate SecretManager pulls GCPSM
  secretStoreRef:
    name: secretstore-aws # name of the SecretStore (or kind specified)
    kind: ClusterSecretStore
  target:
    name: project-example # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: project-example  # name of the GCPSM secret key
      remoteRef:
        key: project-example
---
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-project_example
  namespace: mberthos
spec:
  hosts:
    - "app.meudomain.com.br"
  gateways:
    - public-gateway
  http:
    - route:
        - destination:
            host: service-helloworld
            subset: aguia
          weight: 80
        - destination:
            host: service-helloworld
            subset: gaviao
          weight: 20
      corsPolicy:
        allowOrigins:
          - exact: "*"
        allowMethods:
          - GET
          - POST
          - PATCH
          - PUT
          - DELETE
          - OPTIONS
        allowCredentials: false
        allowHeaders:
          - "*"