apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-example
  labels:
    app: project-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-example
  template:
    metadata:
      labels:
        app: project-example
    spec:
      containers:
        - name: project-example
          image: 767828761310.dkr.ecr.us-east-2.amazonaws.com/hotmart-sre:1.0.1
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: project-example

---
apiVersion: v1
kind: Service
metadata:
  name: project-example
  labels:
    logging: loki
    app: project-example
    service: project-example
spec:
  selector:
    app: project-example
  ports:
    - port: 80
      name: http
      targetPort: 80
---
apiVersion: v1
data:
  APPINSIGHTS_INSTRUMENTATIONKEY: NDZkYjU4M
kind: Secret
metadata:
  name: project-example
  namespace: carguero-homolog
type: Opaque