apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: wise
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
