apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: mynamespace
spec:
  source:
    path: './myapp/'
    targetRevision: HEAD
  destination:
    name: ''
    namespace: mynamespace
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true