apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: master-apps-dev
  namespace: argocd
spec:
  destination:
    name: 'in-cluster'
    namespace: argocd
    server: ''
  source:
    path: ./argocd-projects/configs/mberthos
    repoURL: 'git@github.com:mberthos/hotmart-idp'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true