redis-ha:
  enabled: false

controller:
  enableStatefulSet: true

server:
  replicas: 1
  env:
    - name: ARGOCD_API_SERVER_REPLICAS
      value: '1'
  extraArgs:
    - --insecure
  config:
    url: "https://argocd.hotmartsre.dev"
    #dex.config: |
    #  connectors:
    #  - type: github
    #    id: github
    #    name: GitHub
    #    config:
    #      clientID: $argocd-github-sso-secret:github.clientID
    #      clientSecret: $argocd-github-sso-secret:github.clientSecret
    #      teamNameField: both
    #          orgs:
    #        - name: mberthos
repoServer:
  replicas: 1