apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-argocd-server
  namespace: argocd
spec:
  hosts:
  - "argocd.hotmart.internal"
  gateways:
  - default/intaernal-gateway
  http:
  - route:
    - destination:
        host: argocd-ha-server
    timeout: 30s