
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eks-dev-binding
subjects:
  - kind: Group
    name: eks-dev-group
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: eks-dev-role
  apiGroup: rbac.authorization.k8s.io