apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eks-dev-role
rules:
  - apiGroups:
      - ""
      - "apps"
      - "batch"
      - "extensions"
    resources:
      - "deployments"
      - "pods"
      - "pods/log"
      - "pods/portforward"
      - "services"
      - "namespace"
    verbs:
      - "get"
      - "list"
      - "describe"