#kubectl edit -n kube-system configmap/aws-auth
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eks-ops-binding
subjects:
  - kind: Group
    name: eks-ops-group
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: eks-ops-role
  apiGroup: rbac.authorization.k8s.io