name: Build and Push to ECR

on:
  workflow_dispatch:
    inputs:
      image_version:
        description: 'Versão da imagem'
        required: true
        default: '1.0.x'
      dockerfile_directory:
        description: 'Diretório do Dockerfile'
        required: true
        default: 'project_example'  # Defina um diretório padrão ou deixe em branco
        type: choice  # Tipo de input como escolha
        options:
          - project_example

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 # Usando a versão mais recente

      - name: Configurar AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login no Amazon ECR
        id: ecr-login
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 767828761310.dkr.ecr.us-east-2.amazonaws.com

      - name: Build da imagem Docker
        run: |
          cd ${{ github.event.inputs.dockerfile_directory }}
          docker build -t hotmart-sre:${{ github.event.inputs.image_version }} .

      - name: Marcar imagem para o Amazon ECR
        run: |
          docker tag hotmart-sre:${{ github.event.inputs.image_version }} 767828761310.dkr.ecr.us-east-2.amazonaws.com/hotmart-sre:${{ github.event.inputs.image_version }}

      - name: Push para o Amazon ECR
        run: |
          docker push 767828761310.dkr.ecr.us-east-2.amazonaws.com/hotmart-sre:${{ github.event.inputs.image_version }}
